<?xml version="1.0" ?>

<robot name="xacro_properties" xmlns:xacro="http://ros.org/wiki/xacro">

<macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
        iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
        izz="${m*r*r/2}"
    />
</macro>

<macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
        iyy="${m*(x*x+z*z)/12}" iyz = "0"
        izz="${m*(x*x+z*z)/12}"
    />
</macro>

<macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
        iyy="${2*m*r*r/5}" iyz = "0"
        izz="${2*m*r*r/5}"
    />
</macro>

<macro name="wheel" params="lr tY">

<link name="${lr}_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="package://roberta_sim/robots/donatello/meshes/${lr}_tire.stl" scale="${wheelRadius*0.001/0.033} ${0.001*wheelWidth/0.018} ${0.001*wheelRadius/0.033}"/>
    </geometry>
    <material name="dark"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<gazebo reference="${lr}_wheel">
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>500000.0</kp>
    <kd>10.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>0.1</maxVel>
    <fdir1>1 0 0</fdir1>
  <material>Gazebo/FlatBlack</material>
</gazebo>


<joint name="${lr}_wheel_joint" type="continuous">
  <parent link="chassis"/>
  <child link="${lr}_wheel"/>
  <origin xyz="${chassisLength/2-wheelPos} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <!--limit effort="100" velocity="100"/>
  <dynamics damping="0.0" friction="0.0"/-->
</joint>

<!--transmission name="${lr}_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${lr}_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="${lr}_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>50</mechanicalReduction>
    </actuator>
  </transmission-->

</macro>

</robot>